wrapper:
    recipe: wrapper|r3d3
    validate_first: True
    max_epochs: 0
arch:
    model:
        root: training_arch
        file: depth_completion/DepthCompletionModel
        # General:
        use_gt_pose: False
        contexts: [[-1, 1], [0], [0]]
        backproject_dim: [ 1, 384, 640 ]
        # Augmentation:
        col_jit_params: [ 0.2, 0.2, 0.2, 0.05 ]
        p_flip: 0.5
        p_zero_inp: 0.2
        disable_automasking: False
        # Masking:
        confidence_thresh: 0.0
        flow_cons_threshold: 3.0
        max_depth_threshold: 200.0
        # Loss weighting:
        weight_tgt_cam: 1.0
        weight_ref_cam: 0.1
        disparity_smoothness: 0.001
        weight_ssim: 0.85
        weight_l1: 0.15
    networks:
        completion:
            recipe: networks/completion|ddad
evaluation:
    depth:
        recipe: evaluation/depth|ddad
    height:
        root: training_arch
        file: HeightMetric
        height_threshold: 0.5
        ratio_threshold: [ 0.005, 0.02, 0.02, 0.02, 0.02, 0.005 ]
        good_frames_split_path: data/splits/ddad/2nd_stage
datasets:
    validation:
        root: [ datasets ]
        name: [ DDADR3D3 ]
        path: [ data/datasets/DDAD ]
        split: [ data/splits/ddad/train.txt  ]
        augmentation:
            resize: [ 384, 640 ]
        dataloader:
            batch_size: 1
            pin_memory: True
            num_workers: 1
        squeeze_sensor: [ False ]
        labels: [ pose, depth, others_pose, others_disp_conf ]
        cameras:
          - [ 'camera_01', 'camera_05', 'camera_06', 'camera_07', 'camera_08', 'camera_09' ]
